### PR TITLE
Update to how we parse UriType.Playlist

### LINKED ISSUE #21: GetMyPlaylists doesnt work
The GetMyPlaylists function doesnt work correctly. Ive got the following error message:
Error converting value "spotify:playlist:3G1AlVTYExPN28BlCxf8GD" to type 'SpotifyWebApi.Model.Uri.SpotifyUri'. Path 'items[0].uri', line 34, position 53.

### PR DESCRIPTION
**Pull request by daveowenatl**
This closes #21

### CODE REVIEW

**Comment by pimmerks** [comment]
I'm not sure if the old notation is deprecated (`spotify:user:<userId>:playlist:<playlistId>`)?

**Comment by daveowenatl** [comment]
For me they're all coming back as `spotify:playlist:<playlistId>`.

**Comment by pimmerks** [comment]
In the Spotify client app, if I right click a playlist > Share > Copy Spotify Uri, I still get the old format though

**Comment by pimmerks** [comment]
Sorry it has been a while, now it looks like the Spotify Uri I get when sharing a playlist is in the `spotify:playlist:<playlistId>` format.
So this PR looks good to me!

**Pull request merged**
